### ISSUE TITLE
Incorrect Dark Scene in Non HDR Video (10bit HEVC)

### ISSUE THREAD

**Issue by wdhwg001** [CarterLi/iina#10]
**System and IINA version:**

- macOS  macOS Monterey 12.1 (MacBook 16" M1 Max)
- IINA  v1.2.0-18

**Expected behavior:**
Test video: magnet:?xt=urn:btih:01f1811270fc29216d9ceb1f19157cc9840ff40c&tr=http%3a%2f%2ft.nyaatracker.com%2fannounce&tr=http%3a%2f%2ftracker.kamigami.org%3a2710%2fannounce&tr=http%3a%2f%2fshare.camoe.cn%3a8080%2fannounce&tr=http%3a%2f%2fopentracker.acgnx.se%2fannounce&tr=http%3a%2f%2fanidex.moe%3a6969%2fannounce&tr=http%3a%2f%2ft.acg.rip%3a6699%2fannounce&tr=https%3a%2f%2ftr.bangumi.moe%3a9696%2fannounce&tr=udp%3a%2f%2ftr.bangumi.moe%3a6969%2fannounce&tr=http%3a%2f%2fopen.acgtracker.com%3a1096%2fannounce&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce
Time: ~16:47
<img width="960" alt="image" src="https://user-images.githubusercontent.com/8943519/147603720-f9d5e892-0a07-47b5-a1a0-06978a84c49a.png">
The image above is captured with original IINA 1.2.
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/8943519/147603989-cc1f3d22-f6e2-4e1b-9d4d-189b5aba8be7.png">
The image above is captured with Infuse 7.3.3947.

**Actual behavior:**
<img width="960" alt="image" src="https://user-images.githubusercontent.com/8943519/147604073-391c40aa-baeb-4bf7-8a57-83073a149ae3.png">
(IINA player flashes from the correct result to this much darker result when it starts)

**Comment by CarterLi** [comment]
Strange...

I got darker image if I have `--icc-profile` set. The same behavior can be reproduced for MPV with `--icc-profile="/Library/ColorSync/Profiles/Displays/Color LCD-37D8832A-2D66-02CA-B9F7-8F30A301B230.icc"` flag

I got the same dark image with original IINA. It was expected because original IINA [sets `--icc-profile` too](https://github.com/iina/iina/blob/develop/iina/VideoView.swift#L252)

**Comment by CarterLi** [comment]
Added a switch to disable ICC profile

![image](https://user-images.githubusercontent.com/6134068/147724478-0f61166d-f2c5-4da9-98ac-7b3b76c99b12.png)

Please have a check

**Comment by wdhwg001** [comment]
That's an odd duck.

Could you reproduce the same behavior in madvr? I'm sorry I couldn't give a shot as I don't have a Windows laptop right now, and m1 doesn't have bootcamp.

**Comment by CarterLi** [comment]
Windows?

**Comment by wdhwg001** [comment]
Yes windows - as madvr could be a reference in terms of renderer with icc profile support (and iirc there're only madvr & mpv have this option).
