### ISSUE TITLE
[Help] Does anyone know how to generate i18n strings using XCode?

### ISSUE THREAD

**Issue by CarterLi** [CarterLi/iina#12]
![image](https://user-images.githubusercontent.com/6134068/147846087-b4b80a05-8a70-4609-83ac-f347de9c1b9a.png)

Generate these pre-translated strings.

**Comment by exgphe** [comment]
Official way:
1. Xcode menu bar Product -> Export Localizations...
2. Translate the exported files
3. Xcode menu bar Product -> Import Localizations...
The strings files are therefore updated by Xcode.

**Comment by CarterLi** [comment]
> Official way:
> 
> 1. Xcode menu bar Product -> Export Localizations...
> 2. Translate the exported files
> 3. Xcode menu bar Product -> Import Localizations...
>    The strings files are therefore updated by Xcode.

感觉不符合我想要的结果。我的需求是：我在 `XXX.xib` 里添加了一个TextField，写了一些英文。然后我想在对应的 `zh-Hant.lproj/XXX.strings` 文件里生成新的对应的格式化字符串，而不要影响已有的字符串。仅此而已。

目前发现最接近我需求的，就是在右侧边栏的 Localization 里面把对应的翻译文件删除然后再创建新的。这是我新添加的TextField也出现了，只不过原有的翻译都丢了。

![image](https://user-images.githubusercontent.com/6134068/147878993-fe5c3a94-2f29-479f-8892-25b30a0f142a.png)
