### ISSUE TITLE
HDR logger subsystem

### ISSUE THREAD

**Issue by low-batt** [CarterLi/iina#15]
**What you want IINA to do:**
Use a "hdr" logger subsystem for HDR related log messages, so log message look like:
```text
18:19:25.544 [hdr][d] Will activate HDR color space instead of using ICC profile
```

**What IINA does currently:**
HDR related log messages use the generic "iina" logger subsystem and include a "HDR:" prefix in the message:
```text
18:03:42.359 [iina][d] HDR: Will activate HDR color space instead of using ICC profile
```

**Why you think this should be added:**
Seems more consistent with how IINA groups log messages that relate to a certain subsystem.

**Comment by CarterLi** [comment]
[Logs in FFmpegController](https://github.com/iina-plus/iina/blob/develop/iina/FFmpegController.m#L473) were not modified
