### ISSUE TITLE
Chapter markings aren't visible when in full screen

### ISSUE THREAD

**Issue by ViRo3** [CarterLi/iina#16]
When the app is windowed, the chapter markings on the playback slider is visible but when in full screen the markings aren't visible 

**System and IINA version:**

- macOS 12.1 (21C52)
- IINA 1.2.0 Build 129

**Expected behavior:**
The markings should be clearly distinct no matter what the background to the OSC is.

**Actual behavior:**

Markings of chapters disappear when in full screen is OSC fulls over black borders. The markings should be distinct no matter the background of the OSC.
<summary>Above</summary>

Refer to attached screenshots : [OSC with chapters in windowed](https://user-images.githubusercontent.com/87166847/148146976-24d46b86-76d4-4a43-9110-31b2772b09ce.png)
[OSC with chapters in full screen](https://user-images.githubusercontent.com/87166847/148147018-353abfa2-93fa-42e7-b738-b7f77e723cbc.png)

- [*] MPV does not have this problem.

**How often does this happen?**
Always

**Comment by robert-corlett** [comment]
The contrast of the chapter markers in the windowed OSC in either dark or light mode is exceptionally poor, and is not visible in the fullscreen OSD when in dark mode. I propose a change, see commit [bc237b1](https://github.com/robert-corlett/iina/commit/bc237b15b1b55e58cdb34f2cb5d1e06e7239f2d6)

- Adjusted the color of chapter markers to blue when in 'dark' mode, which improves visibility across both windowed and fullscreen contexts.
- Darkened the color of chapter markers slightly when in 'light' mode to ensure sufficient contrast. 

What do y'all think?
