### ISSUE TITLE
Release triggers alert from app due to suspected Dylib injection

### ISSUE THREAD

**Issue by ViRo3** [CarterLi/iina#2]
The [app](https://github.com/theevilbit/Shield) triggers an alert for this repo's release of Iina causing it to crash; doesn't happen with official releases
[IINA-2021-11-24-205014.txt](https://github.com/CarterLi/iina-hdr/files/7596884/IINA-2021-11-24-205014.txt)

A fix would be very appreciated!

**Comment by CarterLi** [comment]
My modification has nothing to do with dylib injection, nor do I know how to fix it.

`libbluray.2.dylib` metioned in the log is boundled inside IINA.app folder, and was built by homebrew. My modification don't use it too ( it's used by MPV afaik )

If you trust my build, add it into the trust list. If not, use the official build instead.

**Comment by CarterLi** [comment]
It's the app that tries to inject IINA. It's not IINA tries to inject others. At least IINA doesn't try to ask for root privileges and  install system global extenions.
