### ISSUE TITLE
make depends fails trying to copy include files

### ISSUE THREAD

**Issue by low-batt** [CarterLi/iina#22]
**System and IINA version:**

- macOS 12.1
- IINA 1.2.0

**Expected behavior:**
make depends is successful

**Actual behavior:**

make depends fails at cp command:
```text
rm -rf deps/include/mpv deps/include/ffmpeg
bash -c 'cp -r "/opt/homebrew/opt/ffmpeg-iina/include/"* deps/include/'
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
make: *** [depends] Error 64
```

**Steps to reproduce:**
Run "make depends"

- [x] MPV does not have this problem.
- [x] [Official IINA](https://github.com/iina/iina) does not have this problem.

**How often does this happen?**
Everytime

**Comment by CarterLi** [comment]
Yes I'm confused by this strange CI issue

`cp -r "/opt/homebrew/opt/ffmpeg-iina/include/"* deps/include/` doesn't seem to be problematic, and works well on my mac

**Comment by CarterLi** [comment]
I'm testing CI with some changes, hence lots of force-push

**Comment by low-batt** [comment]
Is that why my commit just disappeared? I had just pushed a fix for iina#3211. I thought it made it in as I remember seeing 100 commits ahead of IINA, but now back to 99. I'll hold off until you give the ok that you have CI working and it is safe to push.

**Comment by low-batt** [comment]
Do you have some special upgraded cp on your Mac? Normally you use captial -R for recursive with cp.

**Comment by low-batt** [comment]
The other build issues I had with make depends seemed to have to do with having already built mpv before. brew wanted reinstall to be used instead of install. Oh, and I'm missing the "create-dmg" app.

**Comment by CarterLi** [comment]
> Do you have some special upgraded cp on your Mac? Normally you use captial -R for recursive with cp.

What the...

I use gnu-coreutils and never know that

**Comment by low-batt** [comment]
Ah. I see cp -r is a gnu-coreutils thing. Also "shell" wasn't recognized for me.

**Comment by CarterLi** [comment]
However [`cp -r` used to work](https://github.com/iina-plus/iina/runs/4812300478?check_suite_focus=true#step:4:223) well

I think I know what the real problem is

**Comment by CarterLi** [comment]
CI is fine now. Closing
