### ISSUE TITLE
ci: suggestion for building a macOS ARM64 binary

### ISSUE THREAD

**Issue by pan93412** [CarterLi/iina#23]
As most of the dynamic libraries IINA use are platform-specific, how about to [apply for a M1 Mac CI](https://www.macstadium.com/opensource)? It seems free for open-source projects like this.

Related: 94379f0ba5b5c5a39cf570db98ae849ab5ba5d40

**Comment by CarterLi** [comment]
Sent a request. Let's see what's next

**Comment by CarterLi** [comment]
@pan93412 I have got a M1 bare metal mac on my account. What can I do next?

<img width="962" alt="image" src="https://user-images.githubusercontent.com/6134068/154925531-37e1f0ca-8130-4389-bceb-013bfa6b58a0.png">

**Comment by pan93412** [comment]
> @pan93412 I have got a M1 bare metal mac on my account. What can I do next?
> 
> <img alt="image" width="962" src="https://user-images.githubusercontent.com/6134068/154925531-37e1f0ca-8130-4389-bceb-013bfa6b58a0.png">

Try this? https://orkadocs.macstadium.com/docs/github-actions

**Comment by CarterLi** [comment]
The guide let me download the IP Plan

<img src="https://files.readme.io/1f60ee8-account-files-select.png">

However I don't have any files to download

<img width="346" alt="image" src="https://user-images.githubusercontent.com/6134068/154927739-86b67371-2591-46bc-a7e4-605bf12925a5.png">

What's wrong?

**Comment by pan93412** [comment]
> The guide let me download the IP Plan
> 
> ![](https://camo.githubusercontent.com/eaf0a486d28be7670541c8e43373b39cbff323b130b8c0c53677454ab25c35ef/68747470733a2f2f66696c65732e726561646d652e696f2f316636306565382d6163636f756e742d66696c65732d73656c6563742e706e67)
> 
> However I don't have any files to download
> 
> <img alt="image" width="346" src="https://user-images.githubusercontent.com/6134068/154927739-86b67371-2591-46bc-a7e4-605bf12925a5.png">
> 
> What's wrong?

🤔 Seems like you don't have Orka subscription? Try the official guide from GitHub instead (but I'm not sure if it can work properly since they do not mention the support of M1): https://docs.github.com/en/actions/hosting-your-own-runners

**Comment by CarterLi** [comment]
I don't even know how to connect the machine 😆

**Comment by pan93412** [comment]
> I don't even know how to connect the machine 😆

Neither am I; I never tried MacStadium before. I think that would be better to ask for their remote support 🤔

**Comment by CarterLi** [comment]
Done
