### ISSUE TITLE
VP9 Videos are broken on Intel builds

### ISSUE THREAD

**Issue by ejkarne** [CarterLi/iina#25]
**System and IINA version:**

- macOS 12.2
- IINA 1.2.0 Build 129

**Expected behavior:**

IINA is able to play VP9 video files.

**Actual behavior:**

IINA displays nothing and freezes if play/pause is pressed.

**Steps to reproduce:**

1. Use a build of IINA that includes FFmpeg 5.0
2. Use an Intel based Mac
3. Wallow in sadness as you can no longer play VP9 videos.

- [X] MPV does not have this problem. (If using pre-5.0 FFmpeg)
- [X] [Official IINA](https://github.com/iina/iina) does not have this problem.

This is actually an [FFmpeg issue](https://trac.ffmpeg.org/ticket/9599) that's affecting IINA since it defaults to hardware acceleration being enabled.

**Comment by CarterLi** [comment]
I don't have an Intel based Mac device.

Does disabling hardware acceleration in preference work for you?

**Comment by ejkarne** [comment]
Yes, disabling hardware acceleration stops the issue from occurring.

**Comment by CarterLi** [comment]
Well, I can't do anything except waiting for ffmpeg fixing this issue. Let's disable hardware acceleration for now or just stuck at [the latest build with ffmpeg 4](https://github.com/iina-plus/iina/actions/runs/1695969519)

**Comment by ValZapod** [comment]
This is this bug upstream. https://trac.ffmpeg.org/ticket/9599#comment:5
