### ISSUE TITLE
Name collision with a different repo, and a homebrew formula

### ISSUE THREAD

**Issue by WoodpeckerBaby** [CarterLi/iina#26]
```
brew install iina-plus
```
This brew formula is not for this repo, which causes a lot of confusion. 

https://formulae.brew.sh/cask/iina-plus 

https://github.com/xjbeta/iina-plus

Would be great if homebrew is supported. Maybe make a brew tap for this repo.

Even better if you guys can negotiate and sort out the name conflict.

**Comment by CarterLi** [comment]
I don't think we want a homebrew formula before someone wants to maintain it.
