### ISSUE TITLE
Build for non-M1 architecture?

### ISSUE THREAD

**Issue by axfelix** [CarterLi/iina#3]
It seems like your builds don't support x86_64, when many EDR-supporting Macs still use that architecture. I haven't actually caught up on M1 Mac build tooling yet so I'm not sure how complicated this is to support, but I'd love to be able to use this branch on my 2018 MBP!

**Comment by CarterLi** [comment]
The problem is that dependencies used by IINA was build by homebrew, which only targets the architecture that homebrew is running on by default.

Don't know how the official binary was build, but you may build it yourself. Just following the official build steps.

**Comment by axfelix** [comment]
OK, Thanks! It might take a while for me to get around to that, but I can do it. I hope it gets easier to ship upstream binaries from this fork, I would really like to see IINA's HDR support improve!
