### ISSUE TITLE
HDR display doesn't look right

### ISSUE THREAD

**Issue by MikeWang000000** [CarterLi/iina#30]
**System and IINA version:**

- macOS 12.1 (21C52)
- IINA v1.2.0-31

**Expected behavior:**
<img width="1440" alt="QuickTime" src="https://user-images.githubusercontent.com/11748152/151316778-0abd85cc-4639-4524-9df2-d1ef1f16b7f9.png">

**Actual behavior:**
<img width="1440" alt="IINA-HDR" src="https://user-images.githubusercontent.com/11748152/151316797-681e87c1-6bdf-409d-bd47-1c090d99a9ae.png">

<br>

**Steps to reproduce:**
Play the file below.
[[Attachment]](https://user-images.githubusercontent.com/11748152/151316985-6c80de56-2986-4bf0-a0ab-a62f7b9d9bbf.mov)

- [x] MPV does not have this problem.
- [x] [Official IINA](https://github.com/iina/iina) does not have this problem.

**How often does this happen?**
Every time

**Comment by CarterLi** [comment]
Sorry for slow respond. I'm currently in holiday and I will test it next week.

However, let's move HDR display related issue to https://github.com/iina-plus/iina/issues/8 for easier bug tracking

**Comment by CarterLi** [comment]
Works for me

![WechatIMG23](https://user-images.githubusercontent.com/6134068/153806609-e69f223d-89d2-4adc-a00c-b82277128de0.jpeg)

Please don't use screenshot to capture the image because screenshot always works on SDR mode, luminance on the result image above SDR range will be clipped.

**Comment by MikeWang000000** [comment]
I am using Macbook Air 2020 (M1). Its built-in display supports HDR according to the official website. It has a smaller maximum nits than the pro, though.
IINA's HDR configuration makes the video overexposed ：（

https://user-images.githubusercontent.com/11748152/153814165-92195f4b-4b1e-4232-8cd5-ddc5b1353f9f.mov

**Comment by MikeWang000000** [comment]
After using --tone-mapping, the overexposure problem is solved.
Probably the same reason as #8.

I'm not very familiar with HDR, sorry for the duplicate issue.

**Comment by CarterLi** [comment]
> It has a smaller maximum nits than the pro, though

What number is that?

**Comment by MikeWang000000** [comment]
## Mac models that support HDR <sup>[🔗](https://support.apple.com/en-us/HT210980)</sup>

These Mac models support HDR video on their built-in display (if applicable) and external HDR10-compatible displays.

 - MacBook Pro introduced in 2018 or later

Model                                                   | Nits (brightness)
--------------------------------------------------------|------------------
MacBook Pro (14-inch, 2021)                             | 1000 (1600 peak)
MacBook Pro (16-inch, 2021)                             | 1000 (1600 peak)
MacBook Pro (13-inch, M1, 2020)                         | 500
MacBook Pro (13-inch, 2020, Two Thunderbolt 3 ports)    | 500
MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)   | 500
MacBook Pro (16-inch, 2019)                             | 500
MacBook Pro (13-inch, 2019, Two Thunderbolt 3 ports)    | 500
MacBook Pro (15-inch, 2019)                             | 500
MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports)   | 500
MacBook Pro (15-inch, 2018)                             | 500
MacBook Pro (13-inch, 2018, Four Thunderbolt 3 ports)   | 500


 - MacBook Air introduced in 2018 or later (HDR on external displays requires a model with Apple silicon)

Model                               | Nits (brightness)
------------------------------------|------------------
MacBook Air (M1, 2020)              | 400
MacBook Air (Retina, 13-inch, 2020) | 400
MacBook Air (Retina, 13-inch, 2019) | 400
MacBook Air (Retina, 13-inch, 2018) | 400


 - iMac introduced in 2020 or later

Model                               | Nits (brightness)
------------------------------------|------------------
iMac (24-inch, M1, 2021)            | 500
iMac (Retina 5K, 27-inch, 2020)     | 500


 - iMac Pro

Model                               | Nits (brightness)
------------------------------------|------------------
iMac Pro                            | 500

 - Mac mini introduced in 2018 or later  
*(No built-in display available)*

 - Mac Pro introduced in 2019  
*(No built-in display available)*
