### ISSUE TITLE
HDR does not work when using HTTP streaming

### ISSUE THREAD

**Issue by ArpitKubadia** [CarterLi/iina#34]
The image on top is when doing HTTP streaming and the one below is when I downloaded that file locally and played it.

![image](https://user-images.githubusercontent.com/19728679/151699997-190f074e-7b03-4cd1-b481-a8dd6f12d93b.png)

HDR is disabled when streaming content with the button to enable/disable it greyed out 
![image](https://user-images.githubusercontent.com/19728679/151700079-adfa5fd9-4129-48b5-bf7e-e0aced2db996.png)

Not sure if this is a bug or a pending feature. Is this fixed in any future release? I am currently on v1.2.0-32

Thank you!

**Comment by hoangtiin** [comment]
Worked on my side. But I have to increase the brightness for a better display.

Disabled HDR

<img width="1840" alt="image" src="https://user-images.githubusercontent.com/86225585/153220287-09ed8df5-2af4-49e1-a3ae-3963f8ecce9f.png">

Enabled HDR
<img width="1840" alt="image" src="https://user-images.githubusercontent.com/86225585/153220199-901faf66-36ad-4026-af72-7cefa8fc36dc.png">

HDR with higher brightness.
<img width="1840" alt="image" src="https://user-images.githubusercontent.com/86225585/153220822-5e9e2279-1937-461c-9bdc-d9d496119813.png">

**Comment by CarterLi** [comment]
Works for me

![image](https://user-images.githubusercontent.com/6134068/153794162-7f5fe3ea-e73e-49aa-a3f8-917b9bb4d10b.png)

Please provide detailed reproduce steps for further discussion

**Comment by ReeganExE** [comment]
> Works for me
> 
> 
> Please provide detailed reproduce steps for further discussion

Seems like it's an issue.

For playing HTTP url, the `Primaries` says it's HDR, but `Colorspace` doesn't. (then the HDR switch is disabled).
 
<img width="495" alt="image" src="https://user-images.githubusercontent.com/7277418/169706525-d7e871e9-d3ea-4dc4-8f8b-ede863b612be.png">

But playing it at local, I get HDR as expected.

<img width="495" alt="image" src="https://user-images.githubusercontent.com/7277418/169706368-6c6aff63-872e-4af5-9bfc-54da8b9eb17b.png">

@CarterLi any idea?

**Comment by ReeganExE** [comment]
Looks like the root cause is from here https://github.com/iina/iina/issues/3806#issuecomment-1154518956.
I just tried the latest IINA+ build (which included this commit ce0de9cd5) on several HDR videos and it worked as expected.

Thanks.
