### ISSUE TITLE
v1.2.0-32 not compatible with Apple Silicon

### ISSUE THREAD

**Issue by qupig** [CarterLi/iina#36]
**System and IINA version:**

- macOS 12.2
- IINA v1.2.0-32

**Expected behavior:**

Like the previous version, it can run directly in the native Apple Silicon environment.

**Actual behavior:**

It shows up as the Intel chip version, suggesting that Rosetta 2 needs to be installed in order to run.

**How often does this happen?**

Always.

**Comment by CarterLi** [comment]
See <https://github.com/iina-plus/iina/issues/17#issuecomment-1026445972>

**Comment by low-batt** [comment]
That is my fault. Working on build issues today. If that goes well I'll be posting a new release that fixes this.

**Comment by qupig** [comment]
That's OK. It's just that you better probably need to revise the description of release to tell people that it's an Intel-only version, lest people keep making bad update attempts like me. Anyway, thank you both for your hard work.

**Comment by low-batt** [comment]
A new release has been published containing IINA+ built for Apple Silicon.

Sorry I took so long fix this. The plan was to quickly change the build and publish a new release, but I had trouble changing the build and CarterLi had to fix my changes. Hopefully this release is good. I have tested it on my M1 and an Intel Mac running macOS 10.15.7.
