### ISSUE TITLE
The current "not compatible with Apple Silicon" DMG is not compatible with Intel

### ISSUE THREAD

**Issue by peterinjapan** [CarterLi/iina#39]
**System and IINA version:**

- macOS 12.1
- IINA [Fix v1.2.0-32 not compatible with Apple Silicon, #36]

**Expected behavior:**
I downloaded and attempted to run on my Intel iMac

**Actual behavior:**
The build is for Apple Silicon, which is an error I believe.

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**
n/a, as I could not run the program on my Intel iMac

- [ ] MPV does not have this problem.
- [ ] [Official IINA](https://github.com/iina/iina) does not have this problem.

**How often does this happen?**

**Comment by CarterLi** [comment]
See https://github.com/iina-plus/iina#binaries
