### ISSUE TITLE
Seems the gamma value is a bit off for certain files

### ISSUE THREAD

**Issue by b0yfriend9** [CarterLi/iina#49]
Hi, when comparing the same file with public release of VLC/ IINA 1.2, I found that image to be tiny bit darker with the latest IINA Plus build found in Actions. This issue seems only exists for certain 264 SDR files. 

**System and IINA version:**

- macOS <12.3.1>
- IINA <latest build from Actions>

**Expected behavior:**
**Actual behavior:**
Can refer to the screenshot here, after slightly lifting the gamma value, the image seems right.
before: https://ibb.co/R4tj6Gr, after: https://ibb.co/89pssWg,
another file before : https://ibb.co/WFgjw8k after: https://ibb.co/phKMMnK

**Comment by CarterLi** [comment]
Did you have ICC profile option disabled?

**Comment by b0yfriend9** [comment]
Emm.. that fixed it.. haha sorry for the trouble..
