### ISSUE TITLE
Xcode build fails due to missing library libz.1.dylib

### ISSUE THREAD

**Issue by low-batt** [CarterLi/iina#5]
**System and IINA version:**

- macOS 12.0.1
- IINA 1.2.0

**Expected behavior:**
Xcode build is successful.

**Actual behavior:**
Xcode build fails with one error:
error: /Users/low-batt/Documents/builds/iina-plus/iina/deps/lib/libz.1.dylib: No such file or directory (in target 'iina' from project 'iina')

I see download_libs.sh was changed to obtain libs from a different place. There seems to be a discrepancy between the libs the new location provides and what the Xcode project expects.

Maybe the new site has been recently updated and no longer provides this library?

This is with Xcode 13.1 on a MacBook Pro with the M1 Max chip trying to build a native IINA.

**Comment by CarterLi** [comment]
Sorry for comfusing. I did not use download_libs.sh since they are outdated, but I built them locally with homebrew.

Check this commit: https://github.com/iina-plus/iina/commit/be499f5f01efe1bbadf535f9d7d22d212994ab51

If there are still dep issues, feel free to update the project file

**Comment by low-batt** [comment]
I believe I have successfully joined iina-plus. :-)

I have been building the dependencies locally but wanted to match up with what iina-plus is doing. I too noticed that the official IINA homebrew repository was updated to build with mpv 0.34.0 and FFmpeg 4.4.1. I've been running with those versions as well. I did notice that last time I ran a full build using the compile.rb not every dependency was building. A few failed with errors. I was hoping the official IINA developers would solve those issues, but have it on my list to come back to.

For iina-plus I will use updated dependencies and adjust the Xcode project locally accordingly.

I'm in a very different time zone from you, on the other side of the world, East coast of the USA.
End of the day here now, so won't accomplish more today.
I will get my latest fix working with iina-plus and commit and push.

Nice to be collaborating with people from other parts of the world! :-)

Closing this issue.

**Comment by CarterLi** [comment]
> I have been building the dependencies locally but wanted to match up with what iina-plus is doing.

I think it's time for me to write new build instructions

> I'm in a very different time zone from you, on the other side of the world, East coast of the USA.

I'm aware of it. Have a good night
