### ISSUE TITLE
When playing a list of videos, only last one will have playback record

### ISSUE THREAD

**Issue by M-Makise-Kurisu** [CarterLi/iina#51]
**System and IINA version:**

- macOS 12.3.1
- IINA 1.2.0 build 129

**Expected behavior:**
All videos are resumable

**Actual behavior:**
Only last video are resumable

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**  

prepare a video list, continuously play at least 2 of them without close window.  
close window
only last video been record.  

- [ ] MPV does not have this problem.
- [ ] [Official IINA](https://github.com/iina/iina) does not have this problem.

**How often does this happen?**
Always

**Comment by CarterLi** [comment]
If it is an issue of the official IINA, please report to them

**Comment by M-Makise-Kurisu** [comment]
Will do
