### ISSUE TITLE
🔴 IINA 1.3.0 BUG: Error Cannot prevent display sleep!

### ISSUE THREAD

**Issue by Thomas-Harrell** [CarterLi/iina#58]
**System and IINA version:**

- macOS Big Sur 11.6.2
- IINA 1.3.0

**Expected behavior:**

**Actual behavior:**

- After running IINA for a period of time, about 2-3 days, there is a high probability of appearing

- After this error, opening the media file, continuing playback after a pause, and dragging the progress bar will all result in this error

- Restore settings and reinstall software did not fix it

- After restarting the computer, the problem can be solved, but after a period of operation, it will reopen again

![01](https://user-images.githubusercontent.com/106761803/174419581-e5730768-39ea-4a12-9b67-c7a5cccfd9ad.png)

<details>
<summary><b>Crash report:</b></summary>

```
Error Cannot prevent display sleep!
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [x] MPV does not have this problem.
- [ ] [Official IINA](https://github.com/iina/iina) does not have this problem.

**How often does this happen?**

- After running IINA for a period of time, about 2-3 days, there is a high probability of appearing

**Comment by CarterLi** [comment]
You should report it to upstream repo
