### ISSUE TITLE
can i get this as a plug for the offical iina? or this is two completely standalone product?

### ISSUE THREAD

**Issue by ghost** [CarterLi/iina#59]
**What you want IINA to do:**
Official IINA supporting HDR

**What IINA does currently:**
no

**Why you think this should be added:**
HDR VIDEO PLAYBACK TO ORIGINAL

**Examples of other projects that have something similar:**

**Comment by CarterLi** [comment]
HDR feature was firstly implemented in this fork, then merged into upstream

This fork contains other bug fixes, not big deal though.
