### ISSUE TITLE
HDR doesn't get detected if video has HDR on a secondary video track and SDR on the default track

### ISSUE THREAD

**Issue by AuroraWright** [CarterLi/iina#6]
If you have a mkv file with more than one video track, and the main track is not HDR, even if you switch to the HDR track IINA doesn't activate HDR and it doesn't show up in the inspector. As an example, I tested this with a mkv containing a both a 1080p SDR and a 4K HDR track. When I used mkvtoolnix to change the mkv header to set the 4k video as default, HDR was correctly detected.

**System and IINA version:**
- macOS  12.0.1 (16" 2021 macbook pro)
- IINA   IINA plus 1.2.0-13

**Expected behavior:**
HDR should be also checked for when changing the video track, not just when the file is opened.

**Actual behavior:**
This doesn't happen currently

<details>
<summary><b>Crash report:</b></summary>

```
```
</details>

<br>

<details>
<summary><b>mpv log:</b></summary>

```
```
</details>

<br>

**Steps to reproduce:**

- [ ] MPV does not have this problem.

**How often does this happen?**

**Comment by CarterLi** [comment]
Yeah. Can you provide a video source for testing?

**Comment by AuroraWright** [comment]
The videos I tested this with are blu-ray remuxes so they're very large (70 GB), but here is one of them https://drive.google.com/file/d/1AzOxXsmA21mLKa_uRgwaiwgO6L4VsJPn/view?usp=sharing

**Comment by CarterLi** [comment]
omg. Can you cut it?

https://github.com/iina/iina/pull/3539#issuecomment-970448151

**Comment by AuroraWright** [comment]
> omg. Can you cut it?
> 
> [iina#3539 (comment)](https://github.com/iina/iina/pull/3539#issuecomment-970448151)

I wasn't sure if you could easily keep HDR  but it turns out mkvtoolnix does it: https://drive.google.com/file/d/1EXtsdtB9QkHlhBxSkMVy155fhzJUnXjv/view?usp=sharing I reproduced the issue with this too

**Comment by CarterLi** [comment]
Thanks for help ( and your luma3ds project too ) 😄 

EDIT: it's still too huge. 3 seconds are enough for testing. I have networking issues accessing google drive and the download speed is very low.

**Comment by AuroraWright** [comment]
Okay, made a 5 seconds one and I also uploaded it to OneDrive (see which one downloads better for you)
https://drive.google.com/file/d/1bBa5dyL7CV0iOXAEvuEaJqGx7LlgixqF/view?usp=sharing
https://1drv.ms/u/s!AnCIzvWkmHOmiS6m3db16oVya767?e=VmhYco

**Comment by CarterLi** [comment]
Try https://github.com/iina-plus/iina/releases/tag/v1.2.0-14

**Comment by AuroraWright** [comment]
Thanks, the issue is fixed!
