### ISSUE TITLE
Compilation failure in MPVController

### ISSUE THREAD

**Issue by low-batt** [CarterLi/iina#62]
**System and IINA version:**

- macOS 12.4
- IINA 1.3.0

**Expected behavior:**
Building using `make` completes successfully.

**Actual behavior:**
Build fails with a compilation error in `MPVController`.  And yet the GitHub builds are working. I'm confused as to why it is failing for me. This is what I'm seeing...

In mpv 0.34.0 [mpv_opengl_init_params](https://github.com/mpv-player/mpv/blob/349e437466163cb52f7d0aa227d4606edd9db501/libmpv/render_gl.h#L106) in `render_gl.h` contains the property `extra_exts`:
```c
    /**
     * This should not be used. It is deprecated and will be removed or ignored
     * when the opengl_cb API is removed.
     */
    const char *extra_exts;
```

In mpv master [mpv_opengl_init_params](https://github.com/mpv-player/mpv/blob/891c9c869f61bfe16e46a9244a6af2ed93f67b23/libmpv/render_gl.h#L106) has been updated, removing this deprecated property.

The IINA method `MPVController.mpvInitRendering` has been updated to not pass `extra_exts` when calling `mpv_opengl_init_params`:
```swift
    var openGLInitParams = mpv_opengl_init_params(get_proc_address: mpvGetOpenGLFunc,
                                                  get_proc_address_ctx: nil)
```

For me this results in a compilation error when I run `make` as the build pulls in the version of `render_gl.h` that still contains `extra_exts`. 

Checking [mpv-iina.rb](https://github.com/iina-plus/homebrew-mpv-iina/blob/9b39921285355d8d7d425fd4c3d4631392260d3d/mpv-iina.rb#L7), IINA+ still seems to be using mpv 0.34.1? And yet `MPVController` has been updated to work with mpv master? I'm confused! What am I doing wrong?

**Steps to reproduce:**
For me all I have to do is run `make`.

- [x] MPV does not have this problem.
- [x] [Official IINA](https://github.com/iina/iina) does not have this problem.

**How often does this happen?**
Everytime.

**Comment by CarterLi** [comment]
I have [upgraded mpv-iina ( for iina+ ) to git head](https://github.com/iina-plus/homebrew-mpv-iina/blob/master/.github/workflows/main.yml#L31) to fix this issue: https://github.com/iina-plus/iina/issues/53

I forgot to update the Makefile
