### ISSUE TITLE
Rebase from upstream IINA

### ISSUE THREAD

**Issue by gotham8x** [CarterLi/iina#65]
<img width="585" alt="image" src="https://user-images.githubusercontent.com/83201216/216817151-6d99dfa3-9d66-4f25-b0b2-d3e69d62a6c3.png">

A bit commits behind from upstream. Should we update?

**Comment by CarterLi** [comment]
https://github.com/iina-plus/iina/issues/4#issuecomment-1148196547

I actually consider archiving this fork, as most of my HDR related commits have been merged into upstream
