### ISSUE TITLE
x64 build failing because deps have expired

### ISSUE THREAD

**Issue by low-batt** [CarterLi/iina#66]
The build tries to download this build of the dependencies:
https://github.com/iina-plus/iina/blob/ab99912e7ded1b1cf4561b0ef35e8f424e162291/.github/workflows/ci.yml#L17

However GitHub only retains builds for 90 days and that dependencies build has expired and is no longer available. A new build of the dependencies needs to be generated and `ci.yml` needs to then be updated to use that build.

The arm64 build is configured to use a self hosted build server and that server seems to be down?

**Comment by CarterLi** [comment]
https://github.com/iina-plus/iina/actions/runs/4311573617

**Comment by immakdas** [comment]
Can you please run the arm build?

**Comment by CarterLi** [comment]
The build server is broken, so no

**Comment by varenc** [comment]
Any x86 builds around these days? :-)
