### ISSUE TITLE
HDR broken on latest release

### ISSUE THREAD

**Issue by avdimdv** [CarterLi/iina#9]
I've updated to the latest release and have HDR disabled at least with the last file I started to watch. Inspector reports colorspace as Unspecified(SDR). Downgrading to previous release work fine.
Here is a couple of seconds sample
https://drive.google.com/file/d/14A6UbjhwrpJsp9Z2Hhp811gDpyA92rSD/view?usp=sharing

**Comment by CarterLi** [comment]
Works for me

![image](https://user-images.githubusercontent.com/6134068/146110097-1f885518-fa43-457e-8b04-d2680878eb4a.png)

**Comment by CarterLi** [comment]
I'm having trouble building IINA because of the [XCode 13.2 bug](https://developer.apple.com/forums/thread/696504), but I have released a binary with what I'm using ( /Application/IINA.app ). Please test it

**Comment by avdimdv** [comment]
Well, I also failed to reproduce bug repeatedly. 

Original case was
1. File played via WiFi on Macbook Pro M1 from SMB share
2. Auto resume was turned on and playback started from approx. chapter start
In such conditions I got no HDR on .14 version and everything is ok on .13
That also applied to small cut I sent to you.

However I failed to reproduce it when small file was stored locally.
And playing big file from network share from the beginning also does not give errors on both versions. 

I will try to compile project myself and debug it.
Though  I am  Windows developer and being new to Macs.

**Comment by avdimdv** [comment]
Damn, had to install Xcode outside Appstore to be able to compile, they just broke it before I even started to test it.
And full Visual Studio is a way easier to use with years of experience against couple of hours in Xcode.

After all I manage to run under debugger.
I don't reproduce bug but there is a definite point when that can happen. 
requestEdrMode() is called twice after opening file, first  from PlayerCore.initVideo() on the stack and at that point of time check of guard mpv.getDouble(MPVProperty.videoParamsSigPeak) > 1.0 will default to SDR being initialised at the moment. 
Second call came from closure #1 in PlayerCore.refreshEdrMode() on the call stack and then colorspace will become corrected.   I suspect that in some rare cases second call will not come or will fail.

If it will I who write the code I will try to avoid unitialised first setting of wrong colorspace at the first place.

**Comment by avdimdv** [comment]
Full call stack on the first an second passes

first

#0	0x000000010031d698 in VideoView.requestEdrMode() at /Users/Shared/SOURCES/iina-plus/iina/iina/VideoView.swift:277
#1	0x000000010031c598 in VideoView.refreshEdrMode() at /Users/Shared/SOURCES/iina-plus/iina/iina/VideoView.swift:268
#2	0x000000010031c368 in VideoView.updateDisplayLink() at /Users/Shared/SOURCES/iina-plus/iina/iina/VideoView.swift:226
#3	0x000000010031b49c in VideoView.startDisplayLink() at /Users/Shared/SOURCES/iina-plus/iina/iina/VideoView.swift:187
#4	0x000000010038c0ec in PlayerCore.initVideo() at /Users/Shared/SOURCES/iina-plus/iina/iina/PlayerCore.swift:368
#5	0x0000000100195f88 in MainWindowController.windowDidLoad() at /Users/Shared/SOURCES/iina-plus/iina/iina/MainWindowController.swift:529
#6	0x0000000100197ce0 in @objc MainWindowController.windowDidLoad() ()
#7	0x00000001882e71b0 in -[NSWindowController _windowDidLoad] ()
#8	0x00000001882e2978 in -[NSWindowController window] ()
#9	0x00000001003894b0 in PlayerCore.openMainWindow(path:url:isNetwork:) at /Users/Shared/SOURCES/iina-plus/iina/iina/PlayerCore.swift:298
#10	0x0000000100387a98 in PlayerCore.open(_:shouldAutoLoad:) at /Users/Shared/SOURCES/iina-plus/iina/iina/PlayerCore.swift:216
#11	0x0000000100388250 in PlayerCore.openURLs(_:shouldAutoLoad:) at /Users/Shared/SOURCES/iina-plus/iina/iina/PlayerCore.swift:254
#12	0x0000000100388790 in PlayerCore.openURL(_:shouldAutoLoad:) at /Users/Shared/SOURCES/iina-plus/iina/iina/PlayerCore.swift:270
#13	0x000000010007ed44 in InitialWindowViewActionButton.mouseDown(with:) at /Users/Shared/SOURCES/iina-plus/iina/iina/InitialWindowController.swift:279
#14	0x000000010007edec in @objc InitialWindowViewActionButton.mouseDown(with:) ()
#15	0x0000000188326874 in -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] ()
#16	0x0000000188299ce4 in -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] ()
#17	0x00000001882990ec in -[NSWindow(NSEventRouting) sendEvent:] ()
#18	0x0000000188298050 in -[NSApplication(NSEvent) sendEvent:] ()
#19	0x000000018855059c in -[NSApplication _handleEvent:] ()
#20	0x00000001881195cc in -[NSApplication run] ()
#21	0x00000001880eac78 in NSApplicationMain ()
#22	0x0000000100225a10 in main at /Users/Shared/SOURCES/iina-plus/iina/iina/AppDelegate.swift:22
#23	0x0000000100fa50f4 in start ()

second

#0	0x0000000102f79788 in VideoView.requestEdrMode() at /Users/Shared/SOURCES/iina-plus/iina/iina/VideoView.swift:279
#1	0x0000000102f78598 in VideoView.refreshEdrMode() at /Users/Shared/SOURCES/iina-plus/iina/iina/VideoView.swift:268
#2	0x0000000102fff708 in closure #1 in PlayerCore.refreshEdrMode() at /Users/Shared/SOURCES/iina-plus/iina/iina/PlayerCore.swift:1249
#3	0x0000000102ceb944 in thunk for @escaping @callee_guaranteed () -> () ()
#4	0x00000001061ffff0 in _dispatch_call_block_and_release ()
#5	0x0000000106201d24 in _dispatch_client_callout ()
#6	0x0000000106214f80 in _dispatch_main_queue_callback_4CF ()
#7	0x0000000185615f00 in __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ ()
#8	0x00000001855d38c0 in __CFRunLoopRun ()
#9	0x00000001855d2734 in CFRunLoopRunSpecific ()
#10	0x000000018e164f68 in RunCurrentEventLoopInMode ()
#11	0x000000018e164cdc in ReceiveNextEventCommon ()
#12	0x000000018e164a9c in _BlockUntilNextEventMatchingListInModeWithFilter ()
#13	0x0000000188128ce0 in _DPSNextEvent ()
#14	0x0000000188127584 in -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] ()
#15	0x00000001881195a4 in -[NSApplication run] ()
#16	0x00000001880eac78 in NSApplicationMain ()
#17	0x0000000102e81a10 in main at /Users/Shared/SOURCES/iina-plus/iina/iina/AppDelegate.swift:22
#18	0x0000000103d690f4 in start ()

**Comment by CarterLi** [comment]
You are right. The `VideoView.updateDisplayLink` path definitely needs revisit. However let's wait for apple fixing the xcode bug first.

**Comment by CarterLi** [comment]
The first path should be avoid by https://github.com/iina-plus/iina/commit/5a9259ac3ed3ce476646167b8a45a89c1bee278d

Try the latest binary please. If you can still reproduce this issue, please open a new issue.
